#!/bin/bash
#
# Test the Ruby S2I image in OpenShift (remote cluster)
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
# VERSION specifies the major version of the Ruby runtime in format of X.Y
# OS specifies RHEL version (e.g. OS=rhel7)
#

THISDIR=$(dirname ${BASH_SOURCE[0]})

source "${THISDIR}/test-lib-ruby.sh"
source "${THISDIR}/test-lib-remote-openshift.sh"

TEST_LIST="\
test_ruby_integration
test_ruby_imagestream
test_ruby_s2i_templates
test_latest_imagestreams
"

trap ct_os_cleanup EXIT SIGINT

ct_os_set_ocp4 || exit $OC_ERR

ct_os_check_compulsory_vars || exit $OC_ERR

ct_os_check_login || exit $OC_ERR

ct_os_tag_image_for_cvp "ruby"

ct_pull_or_import_postgresql || exit $OC_ERR

set -u

# For testing on OpenShift 4 we use internal registry
export CT_OCP4_TEST=true

TEST_SUMMARY=''
TEST_SET=${TESTS:-$TEST_LIST} ct_run_tests_from_testset "openshift-remote-cluster"
# vim: set tabstop=2:shiftwidth=2:expandtab:

