FROM ubi8/ruby-27

# Add application sources to a directory that the assemble script expects them
# and set permissions so that the container runs without root access
USER 0
ADD app-src /tmp/src
RUN chown -R 1001:0 /tmp/src
USER 1001

ENV RAILS_ENV=development
# Install the dependencies
RUN bash -c "/tmp/src/.s2i/bin/assemble || /usr/libexec/s2i/assemble"

# Set the default command for the resulting image
CMD /usr/libexec/s2i/run
